### ISSUE TITLE
Recent changes to bitcoin library breaks encryption. 

### ISSUE THREAD

**Issue by jonlundy** [sour-is/bip38tool#1]

**Comment by rplevy** [comment]
It worked for me at an earlier version. Can you provide more detail? It sounds like you are saying that an update to a non-versioned dependency is now broken?

**Comment by jonlundy** [comment]
Thanks for asking! When I found the bug i put up the notice. I wasn't sure if anyone was even using this project, but wanted to make sure to warn anyone if they came across it before I could push the fix. I went back through the library and wrote full end to end testing of the libraries. 

The error was found here: https://github.com/sour-is/bitcoin/blob/master/bip38/bip38.go#L20

where on encrypting it was using the public key to generate the salt value rather than the wallet address. I have fixed and pushed up the changes made..

It would definitely be a good idea to pin to verified working versions to avoid breakage like this in the future.

**Comment by rplevy** [comment]
Great! Thanks for sharing this code by the way, it was useful to me.
